<?php
if($row_log['linked_action'] != "0") {

 switch ($row_log['linked_action']) {
               case 1;
                  $log = ucfirst($LANG['log'][98]).': '.$row_log['new_value'];
                  break;
               case 2;
                  $log = ucfirst($LANG['log'][99]).': '.$row_log['new_value'];
                  break;  
					case 3;
                  $log = ucfirst($LANG['log'][22]).': '.$row_log['old_value'];
                  break; 
               case 4;
                  $log = ucfirst($LANG['log'][110]).': '.$row_log['new_value'];
                  break; 
               case 5;
                  $log = ucfirst($LANG['log'][111]).': '.$row_log['old_value'];
                  break; 
               case 6;
                  $log = ucfirst($LANG['log'][26]).': '.$row_log['old_value'];
                  break; 
               case 7;
//                  $log = ucfirst($LANG['log'][27]).': '.$row_log['new_value'];
					   $log = ucfirst($LANG['buttons'][39]).': '.$row_log['old_value'].' '.$row_log['new_value'] ;
                  break;
               case 8;
                  $log = ucfirst($LANG['log'][125]).': '.$row_log['old_value'];
                  break;
               case 9;
                  $log = ucfirst($LANG['log'][125]).': '.$row_log['new_value'];
                  break;   
 					case 12;
                  $log = ucfirst($LANG['log'][125]).': '.$row_log['new_value'];
                  break;                                                                   
					case 13;
                  $log = ucfirst($LANG['log'][100]).': '.$row_log['new_value'];
                  break;                   
					case 14;
                  $log = ucfirst($LANG['log'][126]).': '.$row_log['new_value'];
                  break;
					case 15;
                  $log = ucfirst($LANG['log'][32]).': '.$row_log['new_value'];
                  break; 
   				case 16;
                  $log = ucfirst($LANG['log'][33]).': '.$row_log['old_value'];
                  break;    
   				case 17;
                  $log = ucfirst($LANG['log'][20]).': '.$row_log['new_value'];
                  break;   
   				case 18;
                  $log = ucfirst($LANG['log'][21]).': '.$row_log['new_value'].' '.$row_log['old_value'];
                  break;
   				case 19;
                  $log = ucfirst($LANG['log'][22]).': '.$row_log['new_value'];
                  break;
   				case 20;
                  $log = ucfirst($LANG['log'][20]).': '.$row_log['new_value'];
                  break; 
   				case 21;
                  $log = ucfirst($LANG['log'][20]).': '.$row_log['new_value'];
                  break;
   				case 22;
                  $log = ucfirst($LANG['log'][127]).': '.$row_log['old_value'];
                  break;
   				case 23;
                  $log = ucfirst($LANG['log'][128]).': '.$row_log['old_value'];
                  break; 
   				case 24;
                  $log = ucfirst($LANG['log'][129]).': '.$row_log['old_value'];
                  break; 
   				case 25;
                  $log = ucfirst($LANG['log'][130]).': '.$row_log['old_value'];
                  break;
   				case 26;
                  $log = ucfirst($LANG['log'][128]).': '.$row_log['old_value'];
                  break; 
   				case 27;
                  $log = ucfirst($LANG['log'][130]).': '.$row_log['old_value'];
                  break;                                                                                                                                                                                                                                   
		}
	}

else {
	
	switch ($row_log['id_search_option']) {
               case 1;
                  $log = ucfirst($LANG['log'][98]).': '.$row_log['new_value'];
                  break;
               case 2;
                  $log = ucfirst($LANG['log'][99]).': '.$row_log['new_value'];
                  break;  
					case 3;
                  $log = ucfirst($LANG['log'][22]).': '.$row_log['old_value'];
                  break; 
               case 4;
                  $log = ucfirst($LANG['log'][110]).': '.$row_log['new_value'];
                  break; 
               case 5;
                  $log = ucfirst($LANG['log'][111]).': '.$row_log['old_value'];
                  break; 
               case 6;
                  $log = ucfirst($LANG['log'][26]).': '.$row_log['old_value'];
                  break; 
               case 7;
                  $log = ucfirst($LANG['buttons'][39]).': '.$row_log['old_value'].' '.$LANG['pager'][7].' '.$row_log['new_value'] ;
                  break;
               case 8;
                  $log = ucfirst($LANG['log'][125]).': '.$row_log['old_value'];
                  break;
               case 9;
                  $log = ucfirst($LANG['log'][125]).': '.$row_log['new_value'];
                  break;   
 					case 12;
                  $log = ucfirst($LANG['log'][125]).': '.$row_log['new_value'];
                  break;                   
					case 14;
                  $log = ucfirst($LANG['log'][126]).': '.$row_log['new_value'];
                  break;
					case 15;
                  $log = ucfirst($LANG['log'][32]).': '.$row_log['new_value'];
                  break; 
   				case 16;
                  $log = ucfirst($LANG['log'][33]).': '.$row_log['old_value'];
                  break;    
   				case 17;
                  $log = ucfirst($LANG['log'][20]).': '.$row_log['new_value'];
                  break;   
   				case 18;
                  $log = ucfirst($LANG['log'][21]).': '.$row_log['new_value'].' '.$row_log['old_value'];
                  break;
   				case 19;
                  $log = ucfirst($LANG['log'][22]).': '.$row_log['old_value'];
                  break;
   				case 20;
                  $log = ucfirst($LANG['log'][20]).': '.$row_log['new_value'];
                  break;    
   				case 21;
                  $log = ucfirst($LANG['log'][20]).': '.$row_log['new_value'];
                  break;
   				case 22;
                  $log = ucfirst($LANG['log'][127]).': '.$row_log['old_value'];
                  break;
   				case 23;
                  $log = ucfirst($LANG['log'][128]).': '.$row_log['old_value'];
                  break; 
   				case 24;
                  $log = ucfirst($LANG['log'][129]).': '.$row_log['old_value'];
                  break; 
   				case 25;
                  $log = ucfirst($LANG['log'][130]).': '.$row_log['old_value'];
                  break;
   				case 26;
                  $log = ucfirst($LANG['log'][128]).': '.$row_log['old_value'];
                  break; 
   				case 27;
                  $log = ucfirst($LANG['log'][130]).': '.$row_log['old_value'];
                  break;                                                                                                                     
		}
	}	

?>